import Trista from './gameSVGs/trista'
import Quest from './gameSVGs/quest'
import Labyrinth from './gameSVGs/labyrinth'
import Wave from './gameSVGs/wave'
import FootballBall from './gameSVGs/footballBall'
import Volleyball from './gameSVGs/volleyball'
import Poker from './gameSVGs/poker'
import PrizeCup from './gameSVGs/prizeCup'
import { RH, RW } from '@/theme/utils'
export const _gamesData = [
  {
    title: 'Игры',
    data: [
      {
        id: 1,
        bigComponent: <Labyrinth width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Labyrinth width={RW(40)} height={RH(40)} top={RH(8)} left={RW(1)} />,
        name: 'Лабиринт',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 2,
        bigComponent: <Quest width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Quest width={RW(50)} height={RH(50)} top={RH(5)} />,
        date: '07.07.22 ',
        name: 'Своя игра',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 3,
        component: <FootballBall width={RW(40)} height={RH(40)} top={RH(10)} left={RW(7)} />,
        bigComponent: <FootballBall width={RW(260)} height={RH(260)} top={RH(0)} />,
        name: 'Футбол',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 4,
        bigComponent: <Trista width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Trista width={RW(40)} height={RH(40)} top={RH(8)} left={RW(9)} />,
        date: '07.07.22 ',
        name: 'Триста',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 5,
        bigComponent: <Volleyball width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Volleyball width={RW(40)} height={RH(40)} top={RH(8)} left={RW(10)} />,
        name: 'Волейбол',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
    ],
  },
  {
    title: 'Топ Игры',
    data: [
      {
        id: 6,
        bigComponent: <Poker width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Poker width={RW(60)} height={RH(40)} top={RH(8)} left={RW(-7)} />,
        name: 'Покер',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 7,
        bigComponent: <Quest width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Quest width={RW(50)} height={RH(50)} top={RH(5)} />,
        date: '07.07.22 ',
        name: 'Своя игра',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 8,
        component: <FootballBall width={RW(40)} height={RH(40)} top={RH(10)} left={RW(7)} />,
        bigComponent: <FootballBall width={RW(260)} height={RH(260)} top={RH(0)} />,
        name: 'Футбол',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 9,
        bigComponent: <Trista width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Trista width={RW(40)} height={RH(40)} top={RH(8)} left={RW(9)} />,
        name: 'Триста',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 10,
        bigComponent: <Volleyball width={RW(260)} height={RH(260)} top={RH(0)} />,
        component: <Volleyball width={RW(40)} height={RH(40)} top={RH(8)} left={RW(10)} />,
        date: '07.07.22 ',
        name: 'Волейбол',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
    ],
  },
  {
    title: 'Турниры',
    data: [
      {
        id: 11,
        bigComponent: (
          <PrizeCup width={RW(260)} height={RH(260)} top={RH(0)} viewBox={'0 0 40 50'} />
        ),
        component: <PrizeCup width={42} height={40} viewBox={'0 0 33 49'} />,
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        players: '10-12',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 12,
        bigComponent: (
          <PrizeCup width={RW(260)} height={RH(260)} top={RH(0)} viewBox={'0 0 40 50'} />
        ),
        component: <PrizeCup width={42} height={40} viewBox={'0 0 33 49'} />,
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 13,
        bigComponent: (
          <PrizeCup width={RW(260)} height={RH(260)} top={RH(0)} viewBox={'0 0 40 50'} />
        ),
        component: <PrizeCup width={42} height={40} viewBox={'0 0 33 49'} />,
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 14,
        bigComponent: (
          <PrizeCup width={RW(260)} height={RH(260)} top={RH(0)} viewBox={'0 0 40 50'} />
        ),
        component: <PrizeCup width={42} height={40} viewBox={'0 0 33 49'} />,
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 15,
        bigComponent: (
          <PrizeCup width={RW(260)} height={RH(260)} top={RH(0)} viewBox={'0 0 40 50'} />
        ),
        component: <PrizeCup width={42} height={40} viewBox={'0 0 33 49'} />,
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
    ],
  },
]
