import Wave from '@/assets/svgs/wave'
import { RH, RW } from '@/theme/utils'
import FootBall from '@/assets/imgs/games/soccer.png'
import Basketball from '@/assets/imgs/games/Basketball.png'
import Mafia from '@/assets/imgs/games/mafia.png'
import Naves from '@/assets/imgs/games/naves.png'
import Poker from '@/assets/imgs/games/poker.png'
import {Image} from "react-native";
import Cup from "@/assets/imgs/Cup.png";
export const _gamesData = [
  {
    title: 'Игры',
    data: [
      {
        id: 1,
        image: FootBall,
        name: 'FootBall',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 2,
        image: Basketball,
        date: '07.07.22 ',
        name: 'Basketball',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 3,
        image: Mafia,
        name: 'Mafia',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 4,
        image: Naves,
        date: '07.07.22 ',
        name: 'Naves',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 5,
        image: Poker,
        name: 'Poker',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
    ],
  },
  {
    title: 'Топ Игры',
    data: [
      {
        id: 6,
        image: FootBall,
        name: 'FootBall',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 7,
        image: Basketball,
        date: '07.07.22 ',
        name: 'Basketball',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 8,
        image: Mafia,
        name: 'Mafia',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 9,
        image: Naves,
        name: 'Naves',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
      {
        id: 10,
        image: Poker,
        date: '07.07.22 ',
        name: 'Poker',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        distantion: '1.6 км',
        players: '10-12',
        playersText: 'Игроки',
        availablePlayers: '12',
        wave: <Wave />,
      },
    ],
  },
  {
    title: 'Турниры',
    data: [
      {
        id: 11,
        image: Cup,
        name: 'Basketball',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        addres: 'наб. 25',
        players: '10-12',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 12,
        image: Cup,
        name: 'Basketball',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 13,
        image: Cup,
        name: 'Basketball',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 14,
        image: Cup,
        name: 'Basketball',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
      {
        id: 15,
        image: Cup,
        name: 'Basketball',
        date: '07.07.22 ',
        gender: 'M',
        time: '18:30 ',
        location: 'Пресненская ',
        playersAge: '25-35',
        players: '10-12',
        addres: 'наб. 25',
        distantion: '1.6 км',
        playersText: 'Игроки',
        playersIn: '12/10',
        wave: <Wave />,
      },
    ],
  },
]
