import React from 'react'
import { View } from 'react-native'

export const GamesData = [
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Футбол.png'),
    date: '7 Ноябрь',
    time: 'May 20,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Баскетбол.png'),
    date: '7 Ноябрь',
    time: 'May 20,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Волейбол.png'),
    date: '8 Ноябрь',
    time: 'May 21,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Навес.png'),
    date: '9 Ноябрь',
    time: 'May 22,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Пионербол.png'),
    date: '9 Ноябрь',
    time: 'May 22,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Триста.png'),
    date: '10 Ноябрь',
    time: 'May 23,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Футбол.png'),
    date: '11 Ноябрь',
    time: 'May 24,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Баскетбол.png'),
    date: '11 Ноябрь',
    time: 'May 24,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Волейбол.png'),
    date: '12 Ноябрь',
    time: 'May 25,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Навес.png'),
    date: '13 Ноябрь',
    time: 'May 26,2022',
  },
  {
    title: '“Название” игры',
    hour: '20:00',
    key: Math.random(),
    img: require('../../screens/Game/gamesDatas.js/gamePics/Пионербол.png'),
    date: '13 Ноябрь',
    time: 'May 26,2022',
  },
]